version: "3"
services:
  pages-ui:
    container_name: pages-ui
    ####################################################################
    # Builds the current code in your repo
    ####################################################################
    build: .
    # DO NOT ADD ENVIRONMENT VARIABLES HERE.
    # New variables should be added to .env.docker
    environment:
      - ENVIRONMENT=docker
    command: yarn start

    ####################################################################
    # Maps port 80 from the container to 8080 on your host, this allows
    # you to access your service via http://localhost:8080.  While we've
    # provided this example here, it's intended as a tool for debugging
    # purposes and not as a permanent bypass for the edge-gateway.
    ####################################################################
    ports:
      - "8083:80"

    ####################################################################
    # Maps your src directory to the /srv/app/src directory in the
    # running docker container.  In theory this would allow for you
    # to use a live-reload solution
    ####################################################################
    volumes:
      - ./:/srv/app
      # - ./uploads:/uploads # For testing s3 upload

########################################################################
# Instructs docker compose to use the invisionlocal_default network
# as the default network for all services in this compose environment
########################################################################
networks:
  default:
    external:
      name: invisionlocal_default
