FROM node:12.14.1-alpine

RUN apk update && \
	apk add --no-cache curl git gnupg make bash python gcc g++  pkgconfig pixman-dev cairo-dev pango-dev libjpeg-turbo-dev giflib-dev
RUN npm i -g node-gyp

WORKDIR /srv/app

# Install node modules (allows for npm install to be cached until package.json changes)
COPY .npmrc .yarnrc package.json yarn.lock tsconfig.json tsconfig.test.json tsconfig.typecheck.json .eslintrc start.sh build.sh ./

# Copy our source files to the service location
COPY src/ ./src
COPY server/ ./server
COPY typings/ ./typings
COPY .git/ ./.git
COPY config/ ./config
COPY public/ ./public
COPY scripts/ ./scripts

# Set default environment variables
ENV \
	PATH=/srv/app:/srv/app/node_modules/.bin:/bin:$PATH\
	DEBUG=false\
	PORT=80

RUN yarn install --frozen-lockfile --build-from-source

RUN ./build.sh

COPY in-config-entrypoint.sh .

# Entrypoint Wrapper generated by EV (see https://invisionapp.atlassian.net/wiki/x/VoSVNQ)
ENTRYPOINT ["./in-config-entrypoint.sh"]
CMD bash -C "./start.sh"
